# Generated by Django 3.0.5 on 2020-05-03 11:48

import apps.guilds.models.profile
from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pw.Server', verbose_name='Сервер')),
            ],
            options={
                'verbose_name': 'Гильдия',
                'verbose_name_plural': 'Гильдии',
                'ordering': ['created_on'],
                'unique_together': {('server', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.guilds.models.profile.Profile.tenant_logo_upload, verbose_name='Логотип')),
                ('cropping', image_cropping.fields.ImageRatioField('logo', '120x120', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Миниатюра')),
                ('wall', models.ImageField(blank=True, null=True, upload_to=apps.guilds.models.profile.Profile.wall_logo_upload, verbose_name='Обложка')),
                ('wall_cropping', image_cropping.fields.ImageRatioField('wall', '1368x472', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Миниатюра')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('guild', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='guilds.Guild', verbose_name='Гильдия')),
            ],
            options={
                'verbose_name': 'Профиль гильдии',
                'verbose_name_plural': 'Профили гильдий',
                'ordering': ['guild'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='guilds.Guild')),
            ],
            options={
                'verbose_name': 'Домен',
                'verbose_name_plural': 'Домены',
            },
        ),
    ]
