# Generated by Django 3.0.5 on 2020-05-12 10:49

import apps.guilds.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=apps.guilds.models.profile.Profile.favicon_logo_upload, verbose_name='favicon'),
        ),
    ]
