# Generated by Django 3.0.5 on 2020-05-03 13:50

import apps.users.models.profile
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=25, verbose_name='Имя')),
                ('date_birthday', models.DateField(blank=True, help_text='Год будет скрыт', null=True, verbose_name='День рождение')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=6, null=True, verbose_name='Пол')),
                ('avatar', image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=apps.users.models.profile.Profile.avatar_upload_image, verbose_name='Аватар')),
                ('avatar_cropping', image_cropping.fields.ImageRatioField('avatar', '124x124', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='avatar cropping')),
                ('wallpaper', image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=apps.users.models.profile.Profile.wallpaper_upload_image, verbose_name='Обложка')),
                ('wallpaper_cropping', image_cropping.fields.ImageRatioField('wallpaper', '1920x624', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='wallpaper cropping')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['user'],
            },
        ),
    ]
