# Generated by Django 3.0.5 on 2020-05-03 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_cropping',
            field=image_cropping.fields.ImageRatioField('avatar', '124x124', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wallpaper_cropping',
            field=image_cropping.fields.ImageRatioField('wallpaper', '1920x624', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Миниатюра'),
        ),
        migrations.CreateModel(
            name='Private',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('name', 'Имя'), ('date_birthday', 'День рождение'), ('gender', 'Пол')], max_length=25, verbose_name='Поле')),
                ('value', models.CharField(choices=[('all', 'Всем'), ('soklan', 'Сокланам'), ('admin', 'Админам')], default='all', max_length=25, verbose_name='Значение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Поле приватности',
                'verbose_name_plural': 'Поля приватности',
                'ordering': ['user'],
                'unique_together': {('user', 'field')},
            },
        ),
    ]
