# Generated by Django 3.0.5 on 2020-05-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200503_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='private',
            options={'ordering': ['user', 'field'], 'verbose_name': 'Поле приватности', 'verbose_name_plural': 'Поля приватности'},
        ),
    ]
