# Generated by Django 3.0.5 on 2020-05-03 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0001_initial'),
        ('users', '0005_auto_20200503_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guild',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guilds.Guild', verbose_name='Гильдия'),
        ),
    ]
