# Generated by Django 3.0.5 on 2020-05-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200508_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='guild',
        ),
    ]
