# Generated by Django 3.0.3 on 2020-05-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_global_admin',
            field=models.BooleanField(default=False, verbose_name='Глобальный администратор'),
        ),
    ]
