# Generated by Django 3.0.5 on 2020-05-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True, verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='')),
            ],
            options={
                'verbose_name': 'Состав',
                'verbose_name_plural': 'Составы',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('soldier', 'Рядовой'), ('captain', 'Капитан'), ('major', 'Майор'), ('marshal', 'Маршал'), ('master', 'Мастер')], max_length=25, unique=True, verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='Права доступа')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
                'ordering': ['sort'],
            },
        ),
    ]
