# Generated by Django 3.0.5 on 2020-05-05 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0002_auto_20200504_1455'),
        ('compositions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soklan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, default='', max_length=50, verbose_name='Должность')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата приема в клан')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chars.Char', verbose_name='Персонаж')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compositions.Composition', verbose_name='Состав')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compositions.Rank', verbose_name='Звание')),
            ],
            options={
                'verbose_name': 'Соклан',
                'verbose_name_plural': 'Сокланы',
                'ordering': ['date_joined'],
            },
        ),
    ]
