# Generated by Django 3.0.5 on 2020-05-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0003_auto_20200505_2307'),
        ('compositions', '0002_soklan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soklan',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chars.Char', verbose_name='Персонаж'),
        ),
    ]
