# Generated by Django 3.0.5 on 2020-05-08 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('compositions', '0006_auto_20200506_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='soklan',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Только администраторы имеют доступ в админ панель', verbose_name='Администратор'),
        ),
        migrations.AddField(
            model_name='soklan',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='Права доступа'),
        ),
        migrations.AlterField(
            model_name='soklan',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soklans', to='compositions.Composition', verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='soklan',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата приема в клан'),
        ),
        migrations.AlterField(
            model_name='soklan',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soklans', to='compositions.Rank', verbose_name='Звание'),
        ),
    ]
