# Generated by Django 3.0.5 on 2020-05-10 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0011_auto_20200508_2252'),
        ('compositions', '0008_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chars.Char', verbose_name='Персонаж'),
        ),
    ]
