# Generated by Django 3.0.5 on 2020-05-10 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0011_auto_20200508_2252'),
        ('compositions', '0009_auto_20200510_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('wait', 'Ожидание'), ('confirm', 'Принят'), ('cancel', 'Отклонено')], default='wait', editable=False, max_length=27, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='SoklanLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Гильдия', (('enter', 'Вступил'), ('left', 'Покинул')))], max_length=27, verbose_name='Событие')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chars.Char', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Действие соклана',
                'verbose_name_plural': 'Действия соклан',
                'ordering': ['-date_created'],
            },
        ),
    ]
