# Generated by Django 3.0.5 on 2020-05-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0010_auto_20200510_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='soklanlog',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
    ]
