# Generated by Django 3.0.5 on 2020-05-11 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compositions', '0011_soklanlog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='soklanlog',
            name='author',
            field=models.ForeignKey(default=1, help_text='Кто совершил событие', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
