# Generated by Django 3.0.5 on 2020-05-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0012_soklanlog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soklanlog',
            name='author',
        ),
        migrations.AlterField(
            model_name='soklanlog',
            name='action',
            field=models.CharField(choices=[('Гильдия', (('enter', 'Вступил в гильдию'), ('left', 'Покинул гильдию')))], max_length=27, verbose_name='Событие'),
        ),
    ]
