# Generated by Django 3.0.5 on 2020-05-12 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chars', '0011_auto_20200508_2252'),
        ('compositions', '0014_auto_20200511_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='soklanlog',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, help_text='Кто совершил действие', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='soklanlog',
            name='action',
            field=models.CharField(choices=[('Гильдия', (('enter', 'Вступил в гильдию'), ('left', 'Покинул гильдию')))], editable=False, max_length=27, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='soklanlog',
            name='char',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='chars.Char', verbose_name='Персонаж'),
        ),
    ]
