# Generated by Django 3.0.5 on 2020-05-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0017_auto_20200512_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
