# Generated by Django 3.0.5 on 2020-05-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegerField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=35, verbose_name='Название')),
                ('help_text', models.CharField(blank=True, default='', max_length=75, verbose_name='Подсказка')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательное поле')),
                ('min', models.IntegerField(verbose_name='Минимальное значение')),
                ('max', models.IntegerField(verbose_name='Максимальное значение')),
            ],
            options={
                'verbose_name': 'Числовое поле',
                'verbose_name_plural': 'Числовые поля',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=35, verbose_name='Название')),
                ('help_text', models.CharField(blank=True, default='', max_length=75, verbose_name='Подсказка')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательное поле')),
            ],
            options={
                'verbose_name': 'Текстовое поле',
                'verbose_name_plural': 'Текстовые поля',
                'ordering': ['pk'],
            },
        ),
    ]
