# Generated by Django 3.0.5 on 2020-05-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constrforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
                'ordering': ['pk'],
            },
        ),
    ]
