# Generated by Django 3.0.5 on 2020-05-11 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constrforms', '0002_requestformmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=35, verbose_name='Название')),
                ('help_text', models.CharField(blank=True, default='', max_length=75, verbose_name='Подсказка')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательное поле')),
            ],
        ),
        migrations.RemoveField(
            model_name='integerfield',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='integerfield',
            name='id',
        ),
        migrations.RemoveField(
            model_name='integerfield',
            name='label',
        ),
        migrations.RemoveField(
            model_name='integerfield',
            name='required',
        ),
        migrations.RemoveField(
            model_name='requestformmodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='id',
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='label',
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='required',
        ),
        migrations.AddField(
            model_name='integerfield',
            name='field_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constrforms.Field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestformmodel',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='constrforms.Field', verbose_name='Поле'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textfield',
            name='field_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constrforms.Field'),
            preserve_default=False,
        ),
    ]
