# Generated by Django 3.0.5 on 2020-05-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constrforms', '0005_auto_20200511_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='')),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='constrforms.Field', verbose_name='Поле')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constrforms.CustomForm', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Поле формы',
                'verbose_name_plural': 'Поля формы',
                'ordering': ['sort'],
            },
        ),
        migrations.DeleteModel(
            name='RequestFormModel',
        ),
    ]
