# Generated by Django 3.0.5 on 2020-05-17 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constrforms', '0006_auto_20200517_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesForField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='customform',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='customform',
            name='title',
            field=models.CharField(max_length=25, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='ChoiceField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constrforms.Field')),
                ('choices', models.ManyToManyField(to='constrforms.ChoicesForField')),
            ],
            options={
                'verbose_name': 'Поле выбора',
                'verbose_name_plural': 'Поля выбора',
                'ordering': ['label'],
            },
            bases=('constrforms.field',),
        ),
    ]
