# Generated by Django 3.0.5 on 2020-05-17 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constrforms', '0007_auto_20200517_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constrforms.Field')),
            ],
            options={
                'verbose_name': 'Поле изображения',
                'verbose_name_plural': 'Поля изображений',
                'ordering': ['label'],
            },
            bases=('constrforms.field',),
        ),
        migrations.AlterField(
            model_name='choicefield',
            name='choices',
            field=models.ManyToManyField(to='constrforms.ChoicesForField', verbose_name='Варианты выбора'),
        ),
    ]
