# Generated by Django 3.0.5 on 2020-05-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constrforms', '0013_auto_20200517_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customform',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='choicefield',
            name='widget',
            field=models.CharField(choices=[('Одиночный выбор', (('field', 'Поле'), ('radio', 'Радиокнопки'))), ('Множественный выбор', (('multifield', 'Поле'), ('checkbox', 'Чекбокс')))], max_length=25, verbose_name='Вид'),
        ),
    ]
