# Generated by Django 3.0.5 on 2020-05-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constrforms', '0014_auto_20200518_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, unique=True, verbose_name='Название страницы')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constrforms.CustomForm', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Страница с заявкой',
                'verbose_name_plural': 'Страницы с заявками',
                'ordering': ['title'],
            },
        ),
    ]
