# Generated by Django 3.0.5 on 2020-05-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constrforms', '0015_requestpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpage',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='constrforms.CustomForm', verbose_name='Форма'),
        ),
    ]
