# Generated by Django 3.0.5 on 2020-05-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constrforms', '0017_auto_20200519_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_close',
            field=models.BooleanField(default=False, verbose_name='Закрыта'),
        ),
    ]
