# Generated by Django 3.0.5 on 2020-05-19 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constrforms', '0018_request_is_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Название')),
                ('action', models.CharField(blank=True, choices=[('Заявка', (('request_open', 'Открыть заявку'), ('request_close', 'Закрывать заявку'))), ('Персонаж', (('invite', 'Принять в клан'),))], max_length=25, null=True, verbose_name='Действие')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constrforms.CustomForm', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'ordering': ['title'],
                'unique_together': {('form', 'title')},
            },
        ),
    ]
