# Generated by Django 3.0.5 on 2020-05-19 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constrforms', '0021_auto_20200519_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='default_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constrforms.RequestStatus', verbose_name='Статус по умолчанию'),
        ),
    ]
