# Generated by Django 3.0.5 on 2020-05-19 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constrforms', '0022_customform_default_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constrforms.Field', verbose_name='Поле'),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('form', 'field')},
        ),
    ]
