# Generated by Django 3.0.5 on 2020-05-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constrforms', '0023_auto_20200519_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='requeststatus',
            name='color',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Цвет'),
        ),
    ]
