# Generated by Django 3.0.3 on 2020-05-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constrforms', '0025_auto_20200519_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfield',
            name='is_multiline',
            field=models.BooleanField(default=False, verbose_name='Многострочное поле'),
        ),
    ]
