# Generated by Django 3.0.3 on 2020-05-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constrforms', '0026_textfield_is_multiline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststatus',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='constrforms.CustomForm', verbose_name='Форма'),
        ),
    ]
