# Generated by Django 3.0.5 on 2020-05-03 11:48

import apps.pw.models.rase
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Название')),
                ('ico', models.ImageField(upload_to=apps.pw.models.rase.Rase.rase_ico_upload_to, verbose_name='Иконка')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Раса',
                'verbose_name_plural': 'Расы',
                'ordering': ['sort', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True, verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Сервера',
                'ordering': ['sort'],
            },
        ),
    ]
