# Generated by Django 3.0.5 on 2020-05-03 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guilds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pw', '0002_auto_20200503_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Char',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Пожалуйста используйте копирабельные никнеймы', max_length=25, verbose_name='Никнейм')),
                ('guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guilds.Guild', verbose_name='Гильдия')),
                ('rase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pw.Rase', verbose_name='Расы')),
                ('server', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pw.Server', verbose_name='Сервер')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ['nickname'],
            },
        ),
    ]
