# Generated by Django 3.0.5 on 2020-05-04 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pw', '0002_auto_20200503_1650'),
        ('chars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char',
            name='rase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pw.Rase', verbose_name='Раса'),
        ),
    ]
