# Generated by Django 3.0.5 on 2020-05-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0001_initial'),
        ('chars', '0003_auto_20200505_2307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='char',
            unique_together={('guild', 'nickname')},
        ),
    ]
