# Generated by Django 3.0.5 on 2020-05-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0005_char_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='char',
            name='permissions',
        ),
    ]
