# Generated by Django 3.0.5 on 2020-05-08 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chars', '0008_auto_20200508_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitechar',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitechar',
            name='char',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='chars.Char', verbose_name='Персонаж'),
        ),
    ]
