# Generated by Django 3.0.5 on 2020-05-08 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0010_auto_20200508_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitechar',
            name='char',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invite', to='chars.Char', verbose_name='Персонаж'),
        ),
    ]
